# Configuration for the Labeler GitHub action, executed by
# .github/workflows/labeler.yml.
#
# The basic syntax is [label]: [path patterns].
#
# For more details on the configuration please see:
# https://github.com/marketplace/actions/labeler

"part:docs": 
  - "**/*.md"
  - "docs/**"
  - "examples/**"
  - LICENSE

"part:tests":
  - "tests/**"

"part:tooling":
  - "**/*.ini"
  - "**/*.toml"
  - "**/*.yaml"
  - "**/*.yml"
  - ".editorconfig"
  - ".git*"
  - ".git*/**"
  - "docs/*.py"
  - CODEOWNERS
  - MANIFEST.in
  - noxfile.py

"part:channels":
  - any:
      - "src/frequenz/channels/**"
      - "!src/frequenz/channels/util/**"

"part:receivers":
  - any:
      - "src/frequenz/channels/util/**"
      - "!src/frequenz/channels/util/_select.py"

"part:select":
  - "src/frequenz/channels/util/_select.py"
