# Configuration for the Labeler GitHub action, executed by
# .github/workflows/labeler.yml.
#
# The basic syntax is [label]: [path patterns].
#
# For more details on the configuration please see:
# https://github.com/marketplace/actions/labeler

"part:docs": 
  - "**/*.md"
  - LICENSE

"part:tests":
  - "tests/**"

"part:tooling":
  - "**/*.ini"
  - "**/*.toml"
  - "*requirements*.txt"
  - ".git*"
  - ".git*/**"
  - CODEOWNERS
  - MANIFEST.in
  - setup.py

"part:channels":
  - any:
      - "src/frequenz/channels/**"
      - "!src/frequenz/channels/select.py"
      - "!src/frequenz/channels/util/**"

"part:receivers":
  - "src/frequenz/channels/util/**"

"part:select":
  - "src/frequenz/channels/select.py"
