[build-system]
requires = [
    "setuptools >= 65.3.0, < 66",
    "setuptools_scm[toml] >= 7.0.5, < 8",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "frequenz-channels"
requires-python = ">= 3.8, < 4"
dependencies = [
    "watchfiles >= 0.15.0",
]
dynamic = [ "version" ]

[[project.authors]]
name ="Frequenz Energy-as-a-Service GmbH"

[tool.setuptools]
include-package-data = true

[tool.setuptools_scm]
version_scheme = "post-release"

[tool.pylint.similarities]
ignore-comments=['yes']
ignore-docstrings=['yes']
ignore-imports=['no']
min-similarity-lines=40

[tool.pylint.messages_control]
# disable wrong-import-order, ungrouped-imports because it conflicts with isort
disable = ["too-few-public-methods", "wrong-import-order", "ungrouped-imports"]
[tool.pylint.'DESIGN']
max-attributes=12

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["src", "examples", "tests"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
required_plugins = [ "pytest-asyncio", "pytest-mock" ]
