name: frequenz-channels-python

on:
  push:
    branches: [ v0.x.x ]

  pull_request:

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Fetch sources
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install required Python packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install nox

    - name: run nox
      run: nox
      timeout-minutes: 10
